repos:
 # Python code formatting
 - repo: https://github.com/astral-sh/ruff-pre-commit
   rev: v0.8.0
   hooks:
   - id: ruff
     args: [--fix]
   - id: ruff-format

 # Type checking with mypy
 - repo: https://github.com/pre-commit/mirrors-mypy
   rev: v1.13.0
   hooks:
   - id: mypy
     additional_dependencies:
     - torch
     - numpy
     - types-requests
     - types-PyYAML
     args: [--strict, --ignore-missing-imports]

 # Security checks
 - repo: https://github.com/PyCQA/bandit
   rev: 1.8.0
   hooks:
   - id: bandit
     args: [-r, .]
     exclude: ^tests/

 # YAML validation
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v5.0.0
   hooks:
   - id: check-yaml
   - id: end-of-file-fixer
   - id: trailing-whitespace
   - id: check-added-large-files
   - id: check-ast
   - id: check-merge-conflict
   - id: check-json
   - id: check-toml
   - id: debug-statements
   - id: detect-private-key

 # Documentation checks
 - repo: https://github.com/pycqa/pydocstyle
   rev: 6.3.0
   hooks:
   - id: pydocstyle
     args: [--convention=google]
     exclude: ^(tests/|scripts/|build/|docs/)

 # Import order checks
 - repo: https://github.com/asottile/reorder-python-imports
   rev: v3.14.0
   hooks:
   - id: reorder-python-imports
     args: [--py38-plus]