max_steps: 2000
batch_size: 1
grad_accum_steps: 4
val_frequency: 200
checkpoint_frequency: 500
early_stopping: false
early_stopping_patience: 10
early_stopping_min_delta: 0.001
lr: 5.0e-05
lr_encoder: 5.0e-06
lr_projector: 1.0e-05
lr_scheduler: cosine
warmup_ratio: 0.1
lr_min_factor: 0.0
weight_decay: 0.0001
amp: true
fp16_eval: false
clip_max_norm: 0.5
dropout: 0.0
drop_path: 0.0
drop_mode: standard
drop_schedule: constant
cutoff_epoch: 0
coco_path: /home/georgepearse/data/cmr/annotations
coco_train: 2025-05-15_12:38:23.077836_train_ordered.json
coco_val: 2025-05-15_12:38:38.270134_val_ordered.json
coco_img_path: /home/georgepearse/data/images
num_workers: 2
resolution: 448
square_resize: true
square_resize_div_64: true
multi_scale: true
expanded_scales: true
test_limit: null
num_classes: 69
encoder: dinov2_windowed_small
pretrain_weights: null
freeze_encoder: false
layer_norm: true
rms_norm: false
backbone_lora: false
hidden_dim: 256
dec_layers: 2
vit_encoder_num_layers: 12
dim_feedforward: 1024
sa_nheads: 8
ca_nheads: 16
group_detr: 13
lite_refpoint_refine: true
num_queries: 100
bbox_reparam: true
out_feature_indexes:
- 2
- 5
- 8
- 11
projector_scale:
- P4
window_block_indexes: null
use_cls_token: false
position_embedding: sine
cls_loss_coef: 1.0
bbox_loss_coef: 5.0
giou_loss_coef: 2.0
focal_alpha: 0.25
mask_loss_coef: 1.0
dice_loss_coef: 1.0
aux_loss: true
sum_group_losses: false
use_varifocal_loss: false
use_position_supervised_loss: false
ia_bce_loss: true
set_cost_class: 2.0
set_cost_bbox: 5.0
set_cost_giou: 2.0
use_ema: true
ema_decay: 0.993
ema_tau: 100.0
output_dir: test_output
dont_save_weights: false
device: cuda
seed: 42
tensorboard: true
wandb: false
project: null
run: null
export_onnx: false
export_torch: true
simplify_onnx: false
opset_version: 17
world_size: 1
dist_url: env://
sync_bn: true
