config:
  amp: true
  aux_loss: true
  backbone_lora: false
  batch_size: 1
  bbox_loss_coef: 5.0
  bbox_reparam: true
  ca_nheads: 16
  checkpoint_frequency: 500
  clip_max_norm: 0.5
  cls_loss_coef: 1.0
  coco_img_path: /home/georgepearse/data/images
  coco_path: /home/georgepearse/data/cmr/annotations
  coco_train: 2025-05-15_12:38:23.077836_train_ordered.json
  coco_val: 2025-05-15_12:38:38.270134_val_ordered.json
  cutoff_epoch: 0
  dec_layers: 2
  device: cuda
  dice_loss_coef: 1.0
  dim_feedforward: 1024
  dist_url: env://
  dont_save_weights: false
  drop_mode: standard
  drop_path: 0.0
  drop_schedule: constant
  dropout: 0.0
  early_stopping: false
  early_stopping_min_delta: 0.001
  early_stopping_patience: 10
  ema_decay: 0.993
  ema_tau: 100.0
  encoder: dinov2_windowed_small
  expanded_scales: true
  export_onnx: false
  export_torch: true
  focal_alpha: 0.25
  fp16_eval: false
  freeze_encoder: false
  giou_loss_coef: 2.0
  grad_accum_steps: 4
  group_detr: 13
  hidden_dim: 256
  ia_bce_loss: true
  layer_norm: true
  lite_refpoint_refine: true
  lr: 5.0e-05
  lr_encoder: 5.0e-06
  lr_min_factor: 0.0
  lr_projector: 1.0e-05
  lr_scheduler: cosine
  mask_loss_coef: 1.0
  max_steps: 2000
  multi_scale: true
  num_classes: 69
  num_queries: 100
  num_workers: 2
  opset_version: 17
  out_feature_indexes:
  - 2
  - 5
  - 8
  - 11
  output_dir: test_output
  position_embedding: sine
  pretrain_weights: null
  project: null
  projector_scale:
  - P4
  resolution: 448
  rms_norm: false
  run: null
  sa_nheads: 8
  seed: 42
  set_cost_bbox: 5.0
  set_cost_class: 2.0
  set_cost_giou: 2.0
  simplify_onnx: false
  square_resize: true
  square_resize_div_64: true
  sum_group_losses: false
  sync_bn: true
  tensorboard: true
  test_limit: null
  use_cls_token: false
  use_ema: true
  use_position_supervised_loss: false
  use_varifocal_loss: false
  val_frequency: 200
  vit_encoder_num_layers: 12
  wandb: false
  warmup_ratio: 0.1
  weight_decay: 0.0001
  window_block_indexes: null
  world_size: 1
