# Strong augmentation configuration for instance segmentation
# Includes more aggressive augmentations suitable for segmentation tasks

train_transforms:
  # Geometric transforms
  - name: HorizontalFlip
    params:
      p: 0.5

  - name: ShiftScaleRotate
    params:
      shift_limit: 0.1
      scale_limit: 0.2
      rotate_limit: 15
      interpolation: 1
      border_mode: 0
      p: 0.5

  # Perspective transform
  - name: Perspective
    params:
      scale: [0.05, 0.1]
      keep_size: true
      p: 0.3

  # Color augmentations
  - name: RandomBrightnessContrast
    params:
      brightness_limit: 0.3
      contrast_limit: 0.3
      p: 0.5

  - name: HueSaturationValue
    params:
      hue_shift_limit: 30
      sat_shift_limit: 40
      val_shift_limit: 30
      p: 0.5

  - name: RGBShift
    params:
      r_shift_limit: 25
      g_shift_limit: 25
      b_shift_limit: 25
      p: 0.3

  # Blur and noise
  - name: OneOf
    params:
      transforms:
        - name: GaussianBlur
          params:
            blur_limit: [3, 7]
        - name: MotionBlur
          params:
            blur_limit: [3, 7]
        - name: MedianBlur
          params:
            blur_limit: [3, 7]
      p: 0.3

  - name: GaussNoise
    params:
      var_limit: [10.0, 50.0]
      p: 0.3

  # Random crop with safe bbox handling
  - name: RandomSizedBBoxSafeCrop
    params:
      height: 800
      width: 800
      erosion_rate: 0.0
      interpolation: 1
      p: 0.7

  # Cutout/CoarseDropout
  - name: CoarseDropout
    params:
      max_holes: 8
      max_height: 32
      max_width: 32
      min_holes: 1
      min_height: 8
      min_width: 8
      fill_value: 0
      p: 0.3

  # Normalize
  - name: Normalize
    params:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  # Convert to tensor
  - name: ToTensorV2

val_transforms:
  # Minimal transforms for validation
  - name: LongestMaxSize
    params:
      max_size: 1333
      interpolation: 1

  - name: PadIfNeeded
    params:
      min_height: 1333
      min_width: 1333
      border_mode: 0
      value: [0, 0, 0]

  - name: Normalize
    params:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  - name: ToTensorV2
