config: !!python/object:rfdetr.training_config.TrainingConfig
  __dict__:
    amp: true
    aux_loss: true
    backbone_lora: false
    batch_size: 1
    bbox_loss_coef: 5.0
    bbox_reparam: true
    ca_nheads: 8
    checkpoint_frequency: 500
    clip_max_norm: 0.1
    cls_loss_coef: 2.0
    coco_img_path: /home/georgepearse/data/images
    coco_path: /home/georgepearse/data/cmr/annotations
    coco_train: 2025-05-15_12:38:23.077836_train_ordered.json
    coco_val: 2025-05-15_12:38:38.270134_val_ordered.json
    cutoff_epoch: 0
    dataset_file: coco
    dec_layers: 2
    device: cuda
    dice_loss_coef: 1.0
    dim_feedforward: 512
    dist_url: env://
    dont_save_weights: false
    drop_mode: standard
    drop_path: 0.0
    drop_schedule: constant
    dropout: 0.0
    early_stopping: false
    early_stopping_min_delta: 0.001
    early_stopping_patience: 5
    ema_decay: 0.9997
    ema_tau: 0
    encoder: dinov2_small
    expanded_scales: false
    export_onnx: false
    export_torch: true
    focal_alpha: 0.25
    fp16_eval: false
    freeze_encoder: false
    giou_loss_coef: 2.0
    grad_accum_steps: 1
    group_detr: 1
    hidden_dim: 128
    ia_bce_loss: false
    layer_norm: true
    lite_refpoint_refine: true
    lr: 5.0e-05
    lr_component_decay: 1.0
    lr_encoder: 5.0e-06
    lr_min_factor: 1.0e-05
    lr_projector: 5.0e-06
    lr_scheduler: cosine
    lr_vit_layer_decay: 0.7
    mask_loss_coef: 1.0
    max_steps: 200
    multi_scale: false
    num_classes: 69
    num_queries: 100
    num_workers: 2
    opset_version: 17
    out_feature_indexes:
    - 9
    - 10
    - 11
    output_dir: output_test_iter_training
    position_embedding: sine
    pretrain_weights: null
    project: null
    projector_scale:
    - P3
    - P4
    - P5
    resolution: 518
    rms_norm: false
    run: null
    sa_nheads: 8
    seed: 42
    set_cost_bbox: 5.0
    set_cost_class: 2.0
    set_cost_giou: 2.0
    simplify_onnx: false
    square_resize: true
    square_resize_div_64: false
    sum_group_losses: false
    sync_bn: true
    tensorboard: true
    test_limit: 100
    two_stage: true
    use_cls_token: false
    use_ema: true
    use_position_supervised_loss: false
    use_varifocal_loss: false
    val_frequency: 200
    vit_encoder_num_layers: 12
    wandb: false
    warmup_ratio: 0.1
    weight_decay: 0.0001
    window_block_indexes: null
    world_size: 1
  __pydantic_extra__: null
  __pydantic_fields_set__: !!set
    amp: null
    batch_size: null
    bbox_reparam: null
    ca_nheads: null
    coco_img_path: null
    coco_path: null
    coco_train: null
    coco_val: null
    dataset_file: null
    dec_layers: null
    dim_feedforward: null
    early_stopping: null
    encoder: null
    grad_accum_steps: null
    group_detr: null
    hidden_dim: null
    layer_norm: null
    lite_refpoint_refine: null
    lr: null
    lr_component_decay: null
    lr_encoder: null
    lr_min_factor: null
    lr_projector: null
    lr_scheduler: null
    lr_vit_layer_decay: null
    max_steps: null
    num_classes: null
    num_queries: null
    num_workers: null
    out_feature_indexes: null
    output_dir: null
    position_embedding: null
    projector_scale: null
    resolution: null
    sa_nheads: null
    tensorboard: null
    test_limit: null
    two_stage: null
    use_cls_token: null
    wandb: null
    warmup_ratio: null
    weight_decay: null
    window_block_indexes: null
  __pydantic_private__: null
