# Configuration for RF-DETR-Mask with fixed image dimensions (896x1232)

# Model Configuration
model:
  encoder: "dinov2_windowed_small"
  out_feature_indexes: [2, 5, 8, 11]
  dec_layers: 3
  two_stage: true
  projector_scale: ["P4"]
  hidden_dim: 256
  sa_nheads: 8
  ca_nheads: 16
  dec_n_points: 2
  bbox_reparam: true
  lite_refpoint_refine: true
  layer_norm: true
  amp: true
  num_classes: 69  # CMR has 69 classes
  pretrain_weights: "rf-detr-base.pth"
  device: "cuda"
  resolution: 896  # Vertical resolution (height)
  group_detr: 13
  gradient_checkpointing: false
  num_queries: 300
  num_select: 300

# Training Configuration
training:
  lr: 5e-5
  lr_encoder: 5e-6
  batch_size: 1
  grad_accum_steps: 4
  epochs: 100
  ema_decay: 0.993
  ema_tau: 100
  lr_drop: 50
  checkpoint_interval: 10
  warmup_epochs: 0
  lr_vit_layer_decay: 0.8
  lr_component_decay: 0.7
  drop_path: 0.0
  group_detr: 13
  ia_bce_loss: true
  cls_loss_coef: 1.0
  num_select: 300
  dataset_file: "coco"
  square_resize_div_64: false  # We'll use our custom fixed size method instead
  fixed_width: 1232  # Width dimension padded to be divisible by 56
  fixed_height: 896  # Height dimension already divisible by 56
  output_dir: "output_fixed_size"
  multi_scale: false
  expanded_scales: false
  use_ema: true
  num_workers: 4
  weight_decay: 1e-4
  early_stopping: false
  early_stopping_patience: 10
  early_stopping_min_delta: 0.001
  early_stopping_use_ema: false
  tensorboard: true
  wandb: false
  
# Dataset Configuration
dataset:
  coco_path: "/home/georgepearse/data/cmr/annotations"
  coco_train: "2025-05-15_12:38:23.077836_train_ordered.json"
  coco_val: "2025-05-15_12:38:38.270134_val_ordered.json"
  coco_img_path: "/home/georgepearse/data/images"
  
# Mask Configuration
mask:
  enabled: true
  loss_mask_coef: 1.0
  loss_dice_coef: 1.0

# Other Configuration
other:
  seed: 42
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  clip_max_norm: 0.5
  steps_per_validation: 0