# Test Configuration for RF-DETR-Mask - Verified Working Config

# Model Configuration
model:
  encoder: "dinov2_windowed_small"  # Using small for quicker testing
  out_feature_indexes: [2, 5, 8, 11]
  dec_layers: 3  # Fewer decoder layers for faster execution
  projector_scale: ["P3", "P4", "P5"]  # Multi-scale projector for better segmentation
  hidden_dim: 256  # Smaller hidden dimension for faster execution
  sa_nheads: 8
  ca_nheads: 16
  dec_n_points: 4
  bbox_reparam: true
  lite_refpoint_refine: true
  layer_norm: true
  amp: false  # Disable AMP for testing - important for stability
  num_classes: 69  # CMR has 69 classes
  pretrain_weights: "rf-detr-base.pth"  # Using base model for testing
  device: "cuda"
  resolution: 560  # Standard resolution for DINOv2 (divisible by 14)
  group_detr: 13
  gradient_checkpointing: false
  num_queries: 300
  num_select: 300

# Training Configuration
training:
  lr: 5e-5
  lr_encoder: 5e-6
  batch_size: 1
  grad_accum_steps: 1
  epochs: 1  # Just 1 epoch for quick testing
  ema_decay: 0.993
  ema_tau: 100
  lr_drop: 1
  checkpoint_interval: 1
  warmup_epochs: 0.1
  lr_vit_layer_decay: 0.8
  lr_component_decay: 0.7
  drop_path: 0.1
  group_detr: 13
  ia_bce_loss: false
  cls_loss_coef: 4.5
  bbox_loss_coef: 2.0
  giou_loss_coef: 1.0
  num_select: 300
  dataset_file: "coco"
  square_resize_div_64: true  # Enable square resize for consistency
  output_dir: "output_test_cmr"
  multi_scale: false  # Disable multi-scale for testing
  expanded_scales: false  # Disable expanded scales for testing
  use_ema: true
  num_workers: 0  # Set to 0 to simplify debugging
  weight_decay: 1e-4
  early_stopping: true
  early_stopping_patience: 3
  early_stopping_min_delta: 0.001
  early_stopping_use_ema: true
  
# Dataset Configuration
dataset:
  coco_path: "/home/georgepearse/data/cmr/annotations"
  coco_train: "2025-05-15_12:38:23.077836_train_ordered.json"
  coco_val: "2025-05-15_12:38:38.270134_val_ordered.json"
  coco_img_path: "/home/georgepearse/data/images"
  
# Mask Configuration
mask:
  enabled: true
  loss_mask_coef: 1.0
  loss_dice_coef: 1.0

# Other Configuration
other:
  seed: 42
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  clip_max_norm: 0.5
  steps_per_validation: 100  # Validate less frequently to finish faster