name: GPU Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests on GPU
    runs-on: gpu-t4-4-core
    timeout-minutes: 60  # Prevent long-running jobs
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Verify GPU
      run: nvidia-smi
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install -e ".[metrics]"
        
    - name: Run tests
      run: python -m unittest discover tests